spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jobpulse?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: jobpulse_user
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true